[theme]
base = "dark"
primaryColor = "#4AA3FF"
backgroundColor = "#050C14"
secondaryBackgroundColor = "#0A1521"
textColor = "#F3F7FB"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
